-- Poblando la tabla tipo de usuarios
INSERT INTO tipo_de_usuario (tipo_de_usuario) VALUES ('administrador');
INSERT INTO tipo_de_usuario (tipo_de_usuario) VALUES ('bodeguero');
INSERT INTO tipo_de_usuario (tipo_de_usuario) VALUES ('registrado');

-- Poblando la tabla usuarios
INSERT INTO usuarios (id_tipo_usuario, nombre, apellido, mail, contrasena) VALUES (1, 'admin', 'bodega', 'admin@admin.cl', '123456');
INSERT INTO usuarios (id_tipo_usuario, nombre, apellido, mail, contrasena) VALUES (2, 'Ignacio', 'Moenen', 'ignacio.moenen@gmail.com', '#Nemesis26');
INSERT INTO usuarios (id_tipo_usuario, nombre, apellido, mail, contrasena) VALUES (3, 'Yessenia', 'Rivera', 'sitayr@gmail.com', 'yesse1234');

-- Poblando la tabla tipo de insumos
INSERT INTO tipo_de_insumo (tipo_de_insumo) VALUES ('QUIRURGICO');
INSERT INTO tipo_de_insumo (tipo_de_insumo) VALUES ('ENDOVENOSO');
INSERT INTO tipo_de_insumo (tipo_de_insumo) VALUES ('MEDICAMENTO');
INSERT INTO tipo_de_insumo (tipo_de_insumo) VALUES ('EPP');

-- Poblando tabla bodegas
INSERT INTO bodegas (nombre_bodega) VALUES ('BODEGA 1');
INSERT INTO bodegas (nombre_bodega) VALUES ('BODEGA 2');
INSERT INTO bodegas (nombre_bodega) VALUES ('BODEGA 3');
INSERT INTO bodegas (nombre_bodega) VALUES ('BODEGA 4');
INSERT INTO bodegas (nombre_bodega) VALUES ('BODEGA 5');

-- Poblando tabla areas / departamentos
INSERT INTO area (nombre_area) VALUES ('POLICLINICO');
INSERT INTO area (nombre_area) VALUES ('OFTALMOLOGÍA');
INSERT INTO area (nombre_area) VALUES ('TRAUMA OCULAR');
INSERT INTO area (nombre_area) VALUES ('SALA HOSPITALIZADOS');
INSERT INTO area (nombre_area) VALUES ('PABELLÓN');

-- Poblando tabla insumos
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'FIBRA DE CHANDELIER'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'FLEX LOOP'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ACEITE SILICONA 1000 CST'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ACEITE SILICONA 5000 CST'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA DE EXTRACCION'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'JERINGA 60 ML LUER LOCK'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'FILTRO DE AIRE 20 MICRAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PERFLUROCARBONO 99%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SILICONA 3.5MM N41.MS N70'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'EXPLANTE # 277'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CONEXION DE SILICONA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA DE PERFLURO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TIP FACOFRAGMENTADOR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'BRILLIANT BLUE'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA G PROBE'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA MP3'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA ENDOSCOPIA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ANILLO ENDOCAPSULAR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'GANCHO DE IRIS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CAPUCHA ROSADA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CAPUCHAS AZULES'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TIP 0.9'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TIP 1.1'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CUCHILLETE 15'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CUCHILLETE 2.4'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CUCHILLETE CRESCENT'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'IRRIGACION ASPIRACION'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'VITECTOR ANTERIOR CENTURION'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'IRRIGACION ASPIRACION'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA 19G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA 21G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA 23G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA 25G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA 27G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA 30G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA PERIBULBAR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA RETROBULBAR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'LASER ILUMINADO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PINZAS ENDODIATERMIAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PINZAS ECKARDT'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PINZAS ASERRADAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PINZAS MICROTIJERAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PIK ENDOILIMINADOR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PUNTAS DE ILM'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PUNTAS ASERRADAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO DRENAJE PENROSE'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PLACA DESECHABLE ELECTROBISTURI'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CABLE BIPOLAR ELECTROBISTURÍ'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA ASPIRACION FRAZIER 10 FR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'LAPIZ MARCADOR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CERA DE HUESO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA CRAFORT'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'AGUJA COLORAO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PARCHE OCULAR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PROTECTOR OCULAR'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'GASA LARGA 6X70 CM 1 ENVOLTORIO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'GASA PLANA 5X5 CM'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'COTONES ESTERILES'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'HISOPO ESTERIL'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'GASA OTORRINO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'PUNZON DE TRANSFERENCIA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'COMPRESA ESTERIL'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'JERINGAS 20CC'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'JERINGAS 10CC'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'JERINGAS 5CC'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'JERINGAS 3CC'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'JERINGAS 1CC'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'WETSSELL PVA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULAS BLANCAS 27 GA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULAS BLANCAS 26 GA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MEMBRANAS AMNIOTICA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'VISCOLASTICOS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'LACRYVISC GEL OFTALMICO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'FLUOROMETOLONA 0,1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'MYDFRIN 2.5%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'CYCLOGYL 1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'MYDRIACYL 1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'TRIAMCINOLONA 40 MG'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'PREDNISOLONA 1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'HIPROMELOSA 0.7%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'PROPARACAINE 0,5%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'MOXIFLOXACINO 0,5%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'PILOCARPINA 4%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'BRIMONIDINA 0,2%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'ATROPINA 1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'TOBRAMICINA 0.3% DEXAMETASONA 0.1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'CLORANFENICOL 0.5%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'KAPH 1%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'BRANULA 16G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'BRANULA 18G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'BRANULA 20G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'BRANULA 22G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'BRANULA 24G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'MARIPOSA 21G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'MARIPOSA 23G'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'TAPAS ROJAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARILLA VENTURI PEDIATRICA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARILLA VENTURI ADULTO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA MAYO #1'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA MAYO #2'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA MAYO # 3'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA MAYO # 4'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA MAYO # 5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ALARGADOR VENOSO 50 CM'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARA LARINGEA #2'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARA LARINGEA #2.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARA LARINGEA #3'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARA LARINGEA #4'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARA LARINGEA #5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CONDUCTOR DE TUBO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'BOUGIE 15 FR 70CM'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CANULA YANKAHUER'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ADAPTADOR T'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ELECTRODOS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA ASPIRACION # 8'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA ASPIRACION # 12'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA ASPIRACION # 14'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA ASPIRACION # 16'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SONDA ASPIRACION # 18'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 2.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 3.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 4.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 5.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 5.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 6.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 6.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 7.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 7.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 8.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 8.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TUBO ENDOTRAQUEAL 9.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'HUMIFICADOR PRELLENADO 500ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARILLA DE NEBULIZACIÓN'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MASCARILLA DE RECIRCULACIÓN'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	2,'LLAVE 3 PASOS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'SEVOFLURANO 250 ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ALARGADOR DE TUBO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ABSORVENTE ANHIDRO CAL SODADA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'FLITRO VERDE CIRCUITO ANESTESIA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'NARICERAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'MANGUERAS DE ASPIRACION 3MT'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'FLEBOS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'BOLSA DE SUCCION 1500ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CIRCUITO PEDIATRICO ANESTESIA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CIRCUITO ADULTO ANESTESIA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES DE PROCEDIMIENTO L'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES DE PROCEDIMIENTO M'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES DE PROCEDIMIENTO S'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES SIN LATEX 6.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES SIN LATEX 7.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES SIN LATEX 7.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES 6.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES 6.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES 7.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES 7.5'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GUANTES ESTÉRILES 8.0'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'SUTURAS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'VISCO ELASTICOS'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'EYE PACK'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ALCOHOL ETILICO 70%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ALCOHOL GEL 75%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ALCOHOL ISOPROPILICO 1 LITRO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ALGODON PRENSADO 1 KILO'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CLORHEXIDINA 2% ACUOSA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CLORHEXIDINA 2% JABONOSA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CLORHEXIDINA 2% TOPICA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'ESCOBILLA LAVADORA QUIRÚRGICA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'POVIDONA YODADA 10% 250 ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'POVIDONA YODADA JABONOSA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'TRICLOSAN JABON 0.5% 1000ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'COMPRESA A GRANEL NO ESTERIL'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'CUBRECALZADO DESECHABLE'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'GORRO QUIRÚRGICO DESECHABLE'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'PECHERA PLASTICA'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	1,'CONTENEDOR CORTOPUNZANTE'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'DELANTAL DESECHABLE TALLA M Y L'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'ESCUDO FACIAL'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'MASCARILLA 3 PLIEGUES DESECHABLES'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'MASCARILLA N95'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	4,'MASCARILLA AURA 3M'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'CLORURO DE SODIO 0.9% 500 ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'MANITOL 15%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'GLUCOSA 10%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'GLUCOSA 5%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'GLUCOSA DEXTROSA 5%'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'CLORURO DE SODIO 0.9 % 1000ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'CLORURO DE POTASIO 1000ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'AGUA BIDESTILADA 500 ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'AGUA BIDESTILADA 1000ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'RINGER LACTATO 500ML'	);
INSERT INTO insumo (id_tipo_insumo, nombre_de_insumo) VALUES (	3,'SUERO FISIOLOGICO 250 ML'	);

